### ISSUE TITLE
Distributed slack bus

### ISSUE THREAD

**Issue by richardkue** [MATPOWER/most#23]
Are there any needs or current developments regarding a distributed slack bus in the power flow calculation?

**Comment by rdzman** [comment]
_Sorry for the delayed response ..._

Since MOST is based on the *optimal* power flow problem, rather than a simple power flow, it does not use the concept of a slack bus at all.

Assuming you are actually referring to distributed slack capabilities in [MATPOWER](https://github.com/MATPOWER/matpower/) (issue tracker [here](https://github.com/MATPOWER/matpower/issues)) as opposed to [MOST](https://github.com/MATPOWER/most), that is in `runpf()`, the answer is that we do not currently have any specific plans under way to add this capability, but would be happy to consider any code contributions toward it.

**Comment by richardkue** [comment]
I meant a distributed slack in runpf and I am thinking about making a contribution.

Is an implementation in one algorithm (e.g. Newton, power, polar) enough to get into a release?

**Comment by richardkue** [comment]
At my own fork of the matpower repository I created a pull request with a concept/idea on how to implement a power flow with distributed slack bus.
I would appreciate it if you have a quick look and can give me some feedback!

**Comment by rdzman** [comment]
If you don't mind, could you please create a new issue in the `matpower` repository and I'll follow up there. Thanks.

**Comment by richardkue** [comment]
I created a new issue in `matpower`. This one can be closed. Sorry for the inconvenience!

**Comment by rdzman** [comment]
Further discussion moved to MATPOWER/matpower#136.
