### ISSUE TITLE
Trying to converte DC Multi-Period OPF to AC Multi-Period OPF

### ISSUE THREAD

**Issue by DiogoFreitas60** [MATPOWER/most#3]
Greetings

On the light of my dissertation where i am trying to study the impact of the addition of battery storage systems to a grid and analyze its impacts on the OPF for the system.

After a conversation with te professor that is guiding me, we talked about trying to use the DC Multi Period OPF from MOST and try to adapt it to work an AC OPF.

Was just posting this here in order to see if anyone would have any idea or suggestion of how to do this

Thank you all for your time
Best Regards

**Comment by rdzman** [comment]
@carlosmurillosanchez, who implemented the early prototypes of MOST, has done some work on AC versions. I'll let him respond with his suggestions.

**Comment by carlosmurillosanchez** [comment]
The original formulation for MOST tried to accomplish the AC version of the algorithm by means of a decomposition involving, on one hand,  a central MIQP problem involving all intertemporal constraints and binary variables, but only a relaxed version of the flow, and on the other hand, AC flows (OPFs) for each operating state in the model.  A decomposition coordination scheme based on the Auxiliary Principle of G. Cohen was then applied to this, using a simple gradient ascent rule for the dual iterations.  This scheme exhibited convergence problems due to the fact that in intertemporally-coupled problems it is possible to have negative nodal prices in some periods and buses, which makes the OPF subproblems unstable.  Not a lot of progress has been made on this until recently, when a PhD student agreed to tackle this problem.  We have been working (starting from the last code that Ray and I shared before Ray transformed it into MOST using the object-oriented problem description mechanism in MATPOWER, and which includes some hydro-specific additions) on re-implementing the whole scheme using an islanding technique and the generalized OPF capabilities in MATPOWER.  This would allow us to solve continuous (no unit commitment) AC problems that fit the MOST paradigm, but it  would work for small problems only.  The reason why we are doing this is so that we  can solve some small-sized problems and then compare upcoming decomposition schemes with known-solved problems.  For the large scale case, we are looking at techniques for the dual update using second order information for the dual iteration;   generalized Benders; and decomposition techniques at the Newton step level of a huge IPM for the whole problem.

I do not know how large are the systems that you want to solve.  Perhaps, when we are done with the islanded implementation, we can share it;  I do not know how viable it will be to include it alonside MOST (it would need extra work to meet the data format, quality standards and provenness already in MOST).

Carlos.

**Comment by DiogoFreitas60** [comment]
Thank you very much for your help and for sharing all that information with
me

Right now im working on small systems, just to try and study the influence
of storage units on the OPF on a 24h case. The professor that is tutoring
suggested we tried using MOST due to the amount of functions it has to
apply a multi period opf (DC OPF). But since the ultimate goal was to study
the same scenario but with a multi period AC OPF, I decided to ask here
just to see if there were any ideas.

Right now im still using the multi period DC OPF in MOST and i previously
tried my own version of a multi period opf in Matpower but adding storage
was kinda tricky

Thank you for sharing your knowledge with me

Em 23/10/2017 21:53, "Carlos E. Murillo-Sanchez" <notifications@github.com>
escreveu:

The original formulation for MOST tried to accomplish the AC version of the
algorithm by means of a decomposition involving, on one hand, a central
MIQP problem involving all intertemporal constraints and binary variables,
but only a relaxed version of the flow, and on the other hand, AC flows
(OPFs) for each operating state in the model. A decomposition coordination
scheme based on the Auxiliary Principle of G. Cohen was then applied to
this, using a simple gradient ascent rule for the dual iterations. This
scheme exhibited convergence problems due to the fact that in
intertemporally-coupled problems it is possible to have negative nodal
prices in some periods and buses, which makes the OPF subproblems unstable.
Not a lot of progress has been made on this until recently, when a PhD
student agreed to tackle this problem. We have been working (starting from
the last code that Ray and I shared before Ray transformed it into MOST
using the object-oriented problem description mechanism in MATPOWER, and
which includes some hydro-specific additions) on re-implementing the whole
scheme using an islanding technique and the generalized OPF capabilities in
MATPOWER. This would allow us to solve continuous (no unit commitment) AC
problems that fit the MOST paradigm, but it would work for small problems
only. The reason why we are doing this is so that we can solve some
small-sized problems and then compare upcoming decomposition schemes with
known-solved problems. For the large scale case, we are looking at
techniques for the dual update using second order information for the dual
iteration; generalized Benders; and decomposition techniques at the Newton
step level of a huge IPM for the whole problem.

I do not know how large are the systems that you want to solve. Perhaps,
when we are done with the islanded implementation, we can share it; I do
not know how viable it will be to include it alonside MOST (it would need
extra work to meet the data format, quality standards and provenness
already in MOST).

Carlos.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MATPOWER/most/issues/3#issuecomment-338793237>, or mute
the thread

**Comment by carlosmurillosanchez** [comment]
Diogo: If you do not need the stochastic aspect of the problem formulation in MOST, then trying to modify MOST to be able to work with AC modeling is probably overkill.  Do you need the stochasticity in renewable generation?  Do you need the N-1 security? The ramp constraints?  Unit commitment?  Market treatment of goods such as reserve and ramp reserve?  Let's first try to decide if you really need the full-fledged MOST capabilities or something simpler, in which case I can guide you on how to implement that using the standard generalized OPF in MATPOWER (and move the discussion out of github).

**Comment by DiogoFreitas60** [comment]
The main objective of my work is to study the influence of storage units on
a multi-period AC OPF.

With this, the goal was to consider Unit Commitment so that we could
achieve a global optimal dispatch value for a period of 24h. It's also
worth mentioning that during this study we would like to take into
consideration the on-off switching costs for generators, the multi-temporal
scenario, trying to link the 24h between themselves so that the OPF doesnt
give an optimal value for each hour, but instead a global optimal point for
the 24h period. We also want to take into consideration Transformers
OLTC's, Capacitor banks optimization and finally, the modelization of the
Storage unit so we can include all this in the study

If you want my email address or any type of contact information, i would be
very glad to provide it

Thank you very much for your help
Best Regards
Diogo

2017-10-23 23:42 GMT+01:00 Carlos E. Murillo-Sanchez <
notifications@github.com>:

**Comment by carlosmurillosanchez** [comment]
DIogo: let's continue this via email at carlos_murillo@ieee.org

**Comment by rdzman** [comment]
Feel free to re-open this issue if there is more discussion that belongs here.
