### ISSUE TITLE
EXITFLAG from price computation stage = -105

### ISSUE THREAD

**Issue by StefanoUnipd** [MATPOWER/most#43]
Using MOST, I noticed that this error often appears. I tried to look into similar issues that had been opened on this platform by others, but without success. How can I try to fix this error?

`CPLEX Version 12.10.0.0 -- default MILP solver`
.
.
.
```
Error using miqps_cplex
miqps_cplex: EXITFLAG from price computation stage = -105

Error in miqps_master (line 207)
            miqps_cplex(H, c, A, l, u, xmin, xmax, x0, vtype, opt);

Error in opt_model/solve (line 230)
                miqps_master(HH, CC, A, l, u, xmin, xmax, x0, vtype, opt);
```

**Comment by rdzman** [comment]
For unit commitment problems, MOST first solves the mixed-integer problem to get the status of the binary commitment variables. However, the MILP and MIQP solvers, such as CPLEX, do not return shadow prices for mixed-integer problems. So, to compute the prices, the integer variables are fixed and the LP or QP problem is re-solved. We call this the "price computation stage". The error you are seeing is because CPLEX did not return a normal success flag. A return value of -105 from `qps_cplex` indicates that CPLEX returned a status code of 5. According to [this page](https://www.ibm.com/docs/en/icos/20.1.0?topic=api-cpx-stat-optimal-infeas) it appears that means ...

_"Optimal solution is available, but with infeasibilities after unscaling."_

I'm not sure of the cause, but it might it seems like a CPLEX issue.

If you don't need to compute prices, the easy solution is to simply disable the price computation stage by setting the `most.skip_prices` to 1.

If you _do_ need the prices, the only things I can suggest are to try a different solver, like Gurobi, or to play around with CPLEX input options (e.g. scaling options) to see if you can find a way to avoid the issue.
